[project]
name = "kf_codegen"
version = "0.1.0"
kind = "lib"

[dependencies]
kf_core = { path = "../kf-core" }
kf_lower = { path = "../kf-lower" }
core = { path = "../../libs/core" }
alloc = { path = "../../libs/alloc" }
std = { path = "../../libs/std" }

[dev-dependencies]
testing = { path = "../../libs/testing" }
