[project]
name = "kf_shared"
version = "0.1.0"
kind = "lib"

[dependencies]
core = { path = "../../libs/core" }
alloc = { path = "../../libs/alloc" }
std = { path = "../../libs/std" }
json = { path = "../../../json" }

[native]
c_sources = ["native/file_hash.c"]
