[project]
name = "kf_reduce"
version = "0.1.0"
kind = "bin"

[dependencies]
core = { path = "../../libs/core" }
alloc = { path = "../../libs/alloc" }
std = { path = "../../libs/std" }

[dev-dependencies]
testing = { path = "../../libs/testing" }
