[project]
name = "kf_lints"
version = "0.1.0"
kind = "lib"

[dependencies]
core = { path = "../../libs/core" }
alloc = { path = "../../libs/alloc" }
kf_core = { path = "../kf-core" }

[dev-dependencies]
testing = { path = "../../libs/testing" }
