[project]
name = "kf_typecheck"
version = "0.1.0"
kind = "lib"

[dependencies]
kf_core = { path = "../kf-core" }
kf_resolve = { path = "../kf-resolve" }
core = { path = "../../libs/core" }
alloc = { path = "../../libs/alloc" }
